### ISSUE TITLE
NOW 2.0

### ISSUE THREAD

**Issue by sctenvoorde** [barryharmsen/register-now-csv#1]
Hi Barry, 

Thanks for your wonderfull dashboard. Are you going to do an update for NOW 2.0 as well?

- Sophie

**Comment by barryharmsen** [comment]
Hi Sophie,

I hadn't yet seen that the new data was released, thanks for bringing it to my attention. I'll probably update the dashboard (and CSV) sometime this week.

Cheers,
Barry

**Comment by barryharmsen** [comment]
The CSV for NOW 2.0 has been added to the repository. Will update the dashboard later.
